### ISSUE TITLE
Deselecting the live filter does not show offline streams

### ISSUE THREAD

**Issue by laurencee** [s1mpl3x/skadi#13] opened 2015-08-20 07:53 UTC
Started with live filter on, turned off the filter but the offline streams do not appear.

**Comment by s1mpl3x** [comment] 2015-08-20 15:09
cant reproduce here, can you post the log and your skadi and java versions + os?

**Comment by laurencee** [comment] 2015-08-21 00:16
Where can I grab a log file from?

I had left the live filter on while watching a few streams, then one of the streams went offline but will still listed on the stream list even though the live filter was on.
Then toggling the live filter no longer worked.

Skadi 2.1.0
Windows 10 pro x64
Java 8 update 60

(Side note, dark theme and tile layout are quite nice :+1: )

**Comment by laurencee** [comment] 2015-08-21 10:55
It happened again just now, I'm pretty sure it's due to a stream going offline while having the live filter on.

**Comment by s1mpl3x** [comment] 2015-08-21 14:32
ok I've still can't really reproduce it, live or text filter on and brought my stream up/down but this didn't trigger any wrong behavior... I'm gonna leave it running the the background for some time now and see if this changes something

You can find the logs in `%USERPROFILE%\.skadi`, but they might not contain any info for this, could you launch skadi with `java -jar Skadi-2.2.0.jar > full_output.txt 2>&1` and try to trigger the error again? the full_output.txt should contain any log output and stacktraces if there are errors

**Comment by s1mpl3x** [comment] 2015-08-21 14:51
OK was able to reproduce now, stacktrace: 

```
Exception in thread "JavaFX Application Thread" java.lang.ArrayIndexOutOfBoundsException: -6
    at javafx.collections.transformation.SortedList.findPosition(SortedList.java:318)
    at javafx.collections.transformation.SortedList.removeFromMapping(SortedList.java:359)
    at javafx.collections.transformation.SortedList.addRemove(SortedList.java:389)
    at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:105)
    at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
    at javafx.collections.transformation.FilteredList.sourceChanged(FilteredList.java:147)
    at javafx.collections.transformation.TransformationList.lambda$getListener$15(TransformationList.java:106)
    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:485)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
    at com.sun.javafx.collections.ObservableListWrapper.access$200(ObservableListWrapper.java:45)
    at com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated(ObservableListWrapper.java:75)
    at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at eu.over9000.skadi.model.Channel.setOnline(Channel.java:222)
    at eu.over9000.skadi.model.Channel.updateOnline(Channel.java:134)
    at eu.over9000.skadi.model.Channel.updateFrom(Channel.java:82)
    at eu.over9000.skadi.service.ChannelUpdateService.lambda$new$15(ChannelUpdateService.java:53)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
    at javafx.concurrent.Service.fireEvent(Service.java:853)
    at javafx.concurrent.Service.lambda$new$491(Service.java:554)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.access$000(ObjectPropertyBase.java:51)
    at javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:233)
    at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at javafx.concurrent.Task.setState(Task.java:696)
    at javafx.concurrent.Task$TaskCallable.lambda$call$501(Task.java:1434)
    at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
```

will look into it, might be related to https://bugs.openjdk.java.net/browse/JDK-8087508

**Comment by s1mpl3x** [comment] 2015-08-27 04:28
I'll leave this open for now as this might be caused by a JDK bug that is triggered by having a tableView displaying a SortedList wrapping a FilteredList where the sort order uses the same properties as the FilteredList.. 

https://github.com/s1mpl3x/skadi/blob/master/src/test/java/eu/over9000/skadi/ui/DebugSortedBug.java
contains a minimal example to trigger this behavior. If the online Column is removed from the sort order of the table it works without problems.

I'll look if there is already a bug filed for this

**Comment by laurencee** [comment] 2015-08-27 04:35
:+1:

**Comment by s1mpl3x** [comment] 2015-09-09 10:14
https://bugs.openjdk.java.net/browse/JDK-8134655 bug report has been closed as duplicate of https://bugs.openjdk.java.net/browse/JDK-8087508 hopefully it will get fixed soon. The workaround i added seems to work so i'll close this for now

**Closed as completed by s1mpl3x** 2015-09-09 10:14 UTC
